### ISSUE TITLE
Game Dev Tycoon v1.6.11

### ISSUE THREAD

**Issue by Ghenghis** [switchlove/GDT-CheatMod#3]
could you update to version v1.6.11 please. I get a mismatch error trying to use currently.

**Comment by switchlove** [comment]
Sorry for the late reply... looking at this, I am showing that this is working without issue on v1.6.15 for all of the features that I have tried. Which feature are you having trouble with?

**Comment by joacommu** [comment]
como me lo descargo▼

**Comment by switchlove** [comment]
Currently this can be downloaded directly via the Steam Workshop here:

https://steamcommunity.com/sharedfiles/filedetails/?id=1128358453
